#!/usr/bin/env python3
"""Aggregate the three engines' latency samples + summaries into charts and a markdown table.

Reads, for each engine, bench/results/<dir>/latencies.csv (one nanosecond per line) and
summary.txt (the harness stderr). Emits latency_tail.png, throughput.png, and summary.md.
"""
import os
import re
import sys

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "bench", "results")

ENGINES = [
    ("Rust", "rust", "#CE422B"),
    ("OCaml — idiomatic", "ocaml_idiomatic", "#1F77B4"),
    ("OCaml — zero-alloc (OxCaml)", "ocaml_oxcaml", "#2CA02C"),
]

PCTS = [50, 90, 99, 99.9, 99.99]
PCT_LABELS = ["p50", "p90", "p99", "p99.9", "p99.99", "max"]


def load_latencies(d):
    path = os.path.join(RESULTS, d, "latencies.csv")
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return np.array(f.read().split(), dtype=np.int64)


def parse_summary(d):
    path = os.path.join(RESULTS, d, "summary.txt")
    info = {"throughput": None, "alloc": None, "median_mps": None}
    if not os.path.exists(path):
        return info
    text = open(path).read()
    m = re.search(r"\(([0-9.]+) M msg/s\)", text)
    if m:
        info["throughput"] = float(m.group(1))
    m = re.search(r"^(ALLOC .*)$", text, re.M)
    if m:
        info["alloc"] = m.group(1).strip()
    m = re.search(r"MEDIAN_MPS=([0-9.]+)", text)
    if m:
        info["median_mps"] = float(m.group(1))
    return info


def main():
    rows = []
    for label, d, color in ENGINES:
        lat = load_latencies(d)
        summ = parse_summary(d)
        if lat is None or lat.size == 0:
            print(f"warning: no latencies for {d}", file=sys.stderr)
            continue
        pct = list(np.percentile(lat, PCTS)) + [float(lat.max())]
        rows.append((label, d, color, lat, pct, summ))

    if not rows:
        print("no data; run scripts/run_all.sh first", file=sys.stderr)
        sys.exit(1)

    # --- chart 1: latency by percentile (the "nines"), log y ---
    plt.figure(figsize=(8, 5))
    xs = range(len(PCT_LABELS))
    for label, d, color, lat, pct, summ in rows:
        plt.plot(xs, pct, marker="o", label=label, color=color, linewidth=2)
    plt.yscale("log")
    plt.xticks(list(xs), PCT_LABELS)
    plt.ylabel("latency per message (ns, log scale)")
    plt.xlabel("percentile")
    plt.title("Per-message latency distribution (lower is better)")
    plt.grid(True, which="both", axis="y", alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(RESULTS, "latency_tail.png"), dpi=130)
    plt.close()

    # --- chart 2: throughput ---
    labels = [r[0] for r in rows]
    tputs = [(r[5]["median_mps"] or r[5]["throughput"] or 0.0) for r in rows]
    colors = [r[2] for r in rows]
    plt.figure(figsize=(8, 4.5))
    bars = plt.bar(labels, tputs, color=colors)
    for b, v in zip(bars, tputs):
        plt.text(b.get_x() + b.get_width() / 2, v, f"{v:.1f}", ha="center", va="bottom")
    plt.ylabel("throughput (million msgs/sec, higher is better)")
    plt.title("Single-core matching throughput")
    plt.xticks(rotation=10)
    plt.tight_layout()
    plt.savefig(os.path.join(RESULTS, "throughput.png"), dpi=130)
    plt.close()

    # --- summary.md ---
    out = []
    out.append("# Benchmark results\n")
    out.append("_Generated by bench/analyze.py from scripts/run_all.sh output._\n")
    out.append("## Latency per message (nanoseconds)\n")
    header = "| Engine | " + " | ".join(PCT_LABELS) + " |"
    out.append(header)
    out.append("|" + "---|" * (len(PCT_LABELS) + 1))
    for label, d, color, lat, pct, summ in rows:
        cells = " | ".join(f"{int(round(v)):,}" for v in pct)
        out.append(f"| {label} | {cells} |")
    out.append("")
    out.append("## Throughput & allocation\n")
    out.append("| Engine | throughput (M msg/s) | allocation |")
    out.append("|---|---|---|")
    for label, d, color, lat, pct, summ in rows:
        t = summ["median_mps"] or summ["throughput"]
        out.append(f"| {label} | {t:.1f} | `{summ['alloc'] or 'n/a'}` |")
    out.append("")
    with open(os.path.join(RESULTS, "summary.md"), "w") as f:
        f.write("\n".join(out))
    print("\n".join(out))
    print(f"\nwrote {RESULTS}/latency_tail.png, throughput.png, summary.md")


if __name__ == "__main__":
    main()
